pipeline:
  name: Staging Deploy
  identifier: staging_deploy
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    environment: staging

  stages:
    - stage:
        name: Staging Deployment
        identifier: staging_deployment
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Print Deployment Context
                  identifier: print_deployment_context
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Starting staging deployment"
                          echo "Branch: <+codebase.branch>"
                          echo "Commit: <+codebase.commitSha>"
                  timeout: 5m

              - step:
                  name: Simulate Staging Deployment
                  identifier: simulate_staging_deployment
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Deploying app to staging..."
                          sleep 3
                          echo "Staging deployment completed."
                  timeout: 5m
