pipeline:
  name: Staging Deploy
  identifier: staging_deploy
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    environment: staging

  stages:
    - stage:
        name: Staging Deployment
        identifier: staging_deployment
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Print Deployment Context
                  identifier: print_deployment_context
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Starting staging deployment"
                      echo "Pipeline: <+pipeline.name>"
                      echo "Stage: <+stage.name>"

              - step:
                  name: Simulate Staging Deployment
                  identifier: simulate_staging_deployment
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Deploying app to staging..."
                      sleep 3
                      echo "Staging deployment completed."
